# Generated by Django 4.2.7 on 2026-06-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='image',
            field=models.ImageField(default='defaults/no-image.png', upload_to='destinations/'),
        ),
    ]
